import { collection, doc, getDoc, getDocs, setDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { mountChrome } from "./shell.js";
import { watchAuth } from "./auth.js";
import { db, configReady } from "./firebase-init.js";
const $ = (id) => document.getElementById(id);
const state = { week: 1, items: [], folders: [], status: "pending", filter: "all", note: { text: "", todos: [] }, uid: null };
const vi = { month: "Th\u00e1ng", unset: "Ch\u01b0a \u0111\u1eb7t h\u1ea1n", none: "Kh\u00f4ng c\u00f3 b\u00e0i ph\u00f9 h\u1ee3p.", saving: "\u0110ang l\u01b0u\u2026", saved: "\u0110\u00e3 l\u01b0u", prompt: "Vi\u1ec7c c\u1ea7n l\u00e0m", teacher: "Gi\u00e1o vi\u00ean" };
const categoryLabels = { "doc-hieu": "\u0110\u1ecdc - hi\u1ec3u", nlxh: "Ngh\u1ecb lu\u1eadn x\u00e3 h\u1ed9i", nlvh: "Ngh\u1ecb lu\u1eadn v\u0103n h\u1ecdc", "de-nam": "\u0110\u1ec1 thi c\u00e1c n\u0103m", "bai-tap": "B\u00e0i t\u1eadp" };
function asDate(v) { if (!v) return null; if (typeof v.toDate === "function") return v.toDate(); if (v.seconds != null) return new Date(v.seconds * 1000); const d = new Date(v); return Number.isNaN(d.getTime()) ? null : d; }
function category(item) { const f = state.folders.find((x) => x.id === item.folderId); if (!f) return "bai-tap"; let r = f; while (r.parentId) r = state.folders.find((x) => x.id === r.parentId) || r; return r.seedKey || (r.kind === "baitap" ? "bai-tap" : r.title); }
function categoryLabel(item) { const key = category(item); return categoryLabels[key] || key; }
function itemStatus(item) { if (item.graded) return "done"; const d = asDate(item.deadline); return d && d.getTime() <= Date.now() ? "pending" : "receiving"; }
function escapeHtml(v) { const e = document.createElement("div"); e.textContent = v || ""; return e.innerHTML; }
function renderCalendar() { const now = new Date(), y = now.getFullYear(), m = now.getMonth(), start = (new Date(y, m, 1).getDay() + 6) % 7, days = new Date(y, m + 1, 0).getDate(); $("calendar-heading").textContent = `${vi.month} ${String(m + 1).padStart(2, "0")} \u00b7 ${y}`; let html = ["T2","T3","T4","T5","T6","T7","CN"].map((x) => `<span class="cal-weekday">${x}</span>`).join(""); for (let i = 0; i < start; i++) html += "<span></span>"; for (let d = 1; d <= days; d++) html += `<span class="cal-day${d === now.getDate() ? " today" : ""}">${d}</span>`; $("mini-calendar").innerHTML = html; }
function renderCounts() { ["pending","receiving","done"].forEach((s) => { $(s + "-count").textContent = state.items.filter((x) => x.type !== "submission" && itemStatus(x) === s).length; }); }
function renderGrading() { const rows = state.items.filter((x) => x.type !== "submission" && itemStatus(x) === state.status && (state.filter === "all" || category(x) === state.filter)); $("grading-list").innerHTML = rows.length ? rows.map((x) => { const d = asDate(x.deadline); const due = d ? new Intl.DateTimeFormat("vi-VN", { day:"2-digit", month:"2-digit", hour:"2-digit", minute:"2-digit", timeZone:"Asia/Ho_Chi_Minh" }).format(d) : vi.unset; return `<div class="grading-row"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(categoryLabel(x))}</small></div><span>${due}</span>${state.status === "done" ? "<span class=\"grade-done\">\u2713</span>" : `<label class="grade-check"><input type="checkbox" data-grade="${x.id}"> \u0110\u00e3 ch\u1ea5m</label>`}</div>`; }).join("") : `<p class="sub">${vi.none}</p>`; document.querySelectorAll("[data-grade]").forEach((input) => input.addEventListener("change", async () => { const item = state.items.find((x) => x.id === input.dataset.grade); item.graded = input.checked; if (configReady && db) await setDoc(doc(db, "practiceItems", item.id), { graded: item.graded }, { merge: true }); renderCounts(); renderGrading(); })); }
function renderNotes() { $("teacher-note").value = state.note.text || ""; $("todo-list").innerHTML = state.note.todos.map((x,i) => `<label class="todo-row"><span class="todo-text ${x.done ? "checked" : ""}">${escapeHtml(x.text)}</span><input type="checkbox" data-todo="${i}" ${x.done ? "checked" : ""} aria-label="Da hoan thanh"></label>`).join(""); document.querySelectorAll("[data-todo]").forEach((input) => input.addEventListener("change", () => { state.note.todos[Number(input.dataset.todo)].done = input.checked; saveNotes(); renderNotes(); })); }
function startTodoEditor() { if ($("todo-editor")) return; const input = document.createElement("input"); input.id = "todo-editor"; input.className = "todo-editor"; input.type = "text"; input.autocomplete = "off"; input.setAttribute("aria-label", "Viec can lam"); $("todo-list").appendChild(input); input.focus(); let saved = false; const commit = () => { if (saved) return; saved = true; const text = input.value.trim(); if (text) { state.note.todos.push({ text, done:false }); saveNotes(); } renderNotes(); }; input.addEventListener("keydown", (e) => { if (e.key === "Enter") { e.preventDefault(); commit(); } if (e.key === "Escape") renderNotes(); }); input.addEventListener("blur", commit); }
async function saveNotes() { if (!state.uid || !configReady || !db) return; $("note-state").textContent = vi.saving; await setDoc(doc(db, "teacherNotes", state.uid), state.note, { merge:true }); $("note-state").textContent = vi.saved; }
async function loadData() { if (!configReady || !db) return; const [f,i] = await Promise.all([getDocs(collection(db,"practiceFolders")),getDocs(collection(db,"practiceItems"))]); state.folders = f.docs.map((x) => ({id:x.id,...x.data()})); state.items = i.docs.map((x) => ({id:x.id,...x.data()})); renderCounts(); renderGrading(); }
function openGrading(status="pending") { state.status=status; $("grading-modal").classList.remove("hidden"); document.querySelectorAll("[data-modal-status]").forEach((x) => x.classList.toggle("on", x.dataset.modalStatus === status)); renderGrading(); }
$("week-prev").onclick=()=>{$("school-week").value=state.week=Math.max(1,state.week-1);}; $("week-next").onclick=()=>{$("school-week").value=++state.week;}; $("school-week").onchange=(e)=>{e.target.value=state.week=Math.max(1,Number(e.target.value)||1);}; $("open-grading").onclick=()=>openGrading(); $("close-grading").onclick=()=>$("grading-modal").classList.add("hidden"); $("grading-modal").onclick=(e)=>{if(e.target===$("grading-modal")) $("grading-modal").classList.add("hidden");}; document.querySelectorAll("[data-status]").forEach((x)=>x.onclick=()=>openGrading(x.dataset.status)); document.querySelectorAll("[data-modal-status]").forEach((x)=>x.onclick=()=>openGrading(x.dataset.modalStatus)); $("grading-filter").onchange=(e)=>{state.filter=e.target.value;renderGrading();}; document.querySelectorAll("[data-note-tab]").forEach((x)=>x.onclick=()=>{const todo=x.dataset.noteTab==="todo";document.querySelectorAll("[data-note-tab]").forEach((b)=>b.classList.toggle("on",b===x));$("note-panel").classList.toggle("hidden",todo);$("todo-panel").classList.toggle("hidden",!todo);}); $("teacher-note").onchange=()=>{state.note.text=$("teacher-note").value;saveNotes();}; $("add-todo").onclick=startTodoEditor;
renderCalendar(); $("school-week").value=state.week; renderNotes(); mountChrome({active:"home",role:"teacher",who:vi.teacher}); watchAuth(async(user,profile)=>{if(!user)return;state.uid=user.uid;mountChrome({active:"home",role:"teacher",who:(profile&&profile.hoTen)||user.email||vi.teacher});if(configReady&&db){const snap=await getDoc(doc(db,"teacherNotes",user.uid));if(snap.exists())state.note={text:"",todos:[],...snap.data()};renderNotes();await loadData();}});
