import { collection, doc, getDoc, getDocs, setDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { mountChrome } from "./shell.js";
import { watchAuth } from "./auth.js";
import { db, configReady } from "./firebase-init.js";
const $ = (id) => document.getElementById(id);
const calendarMin = { year: 2024, month: 0 }, calendarMax = { year: 2030, month: 11 };
const today = new Date();
const initialCalendar = { year: Math.min(calendarMax.year, Math.max(calendarMin.year, today.getFullYear())), month: today.getMonth() };
const state = { week: 1, items: [], folders: [], status: "pending", filter: "all", note: { text: "", todos: [] }, uid: null, deleteMode: false, calendar: initialCalendar };
const vi = { month: "Th\u00e1ng", unset: "Ch\u01b0a \u0111\u1eb7t h\u1ea1n", none: "Kh\u00f4ng c\u00f3 b\u00e0i ph\u00f9 h\u1ee3p.", saving: "\u0110ang l\u01b0u\u2026", saved: "\u0110\u00e3 l\u01b0u", prompt: "Vi\u1ec7c c\u1ea7n l\u00e0m", teacher: "Gi\u00e1o vi\u00ean" };
const categoryLabels = { "doc-hieu": "\u0110\u1ecdc - hi\u1ec3u", nlxh: "Ngh\u1ecb lu\u1eadn x\u00e3 h\u1ed9i", nlvh: "Ngh\u1ecb lu\u1eadn v\u0103n h\u1ecdc", "de-nam": "\u0110\u1ec1 thi c\u00e1c n\u0103m", "bai-tap": "B\u00e0i t\u1eadp" };
function asDate(v) { if (!v) return null; if (typeof v.toDate === "function") return v.toDate(); if (v.seconds != null) return new Date(v.seconds * 1000); const d = new Date(v); return Number.isNaN(d.getTime()) ? null : d; }
function category(item) { const f = state.folders.find((x) => x.id === item.folderId); if (!f) return "bai-tap"; let r = f; while (r.parentId) r = state.folders.find((x) => x.id === r.parentId) || r; return r.seedKey || (r.kind === "baitap" ? "bai-tap" : r.title); }
function categoryLabel(item) { const key = category(item); return categoryLabels[key] || key; }
function itemStatus(item) { if (item.graded) return "done"; const d = asDate(item.deadline); return d && d.getTime() <= Date.now() ? "pending" : "receiving"; }
function escapeHtml(v) { const e = document.createElement("div"); e.textContent = v || ""; return e.innerHTML; }
function isCalendarBoundary(date, boundary) { return date.year === boundary.year && date.month === boundary.month; }
function renderCalendar() { const { year: y, month: m } = state.calendar, start = (new Date(y, m, 1).getDay() + 6) % 7, days = new Date(y, m + 1, 0).getDate(), isCurrentMonth = y === today.getFullYear() && m === today.getMonth(); $("calendar-heading").textContent = `${vi.month} ${String(m + 1).padStart(2, "0")} \u00b7 ${y}`; $("calendar-prev").disabled = isCalendarBoundary(state.calendar, calendarMin); $("calendar-next").disabled = isCalendarBoundary(state.calendar, calendarMax); let html = ["T2","T3","T4","T5","T6","T7","CN"].map((x) => `<span class="cal-weekday">${x}</span>`).join(""); for (let i = 0; i < start; i++) html += "<span></span>"; for (let d = 1; d <= days; d++) { const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`, note=(state.calendarNotes||{})[key]; html += `<button type="button" class="cal-day${isCurrentMonth && d === today.getDate() ? " today" : ""}${note ? " has-note" : ""}" data-calendar-note="${key}"${note ? ` title="${escapeHtml(note)}"` : ""}>${d}</button>`; } $("mini-calendar").innerHTML = html; document.querySelectorAll("[data-calendar-note]").forEach((el)=>el.oncontextmenu=async(e)=>{e.preventDefault();const text=window.prompt("Thêm note",(state.calendarNotes||{})[el.dataset.calendarNote]||"");if(text===null)return;state.calendarNotes=state.calendarNotes||{};if(text.trim())state.calendarNotes[el.dataset.calendarNote]=text.trim();else delete state.calendarNotes[el.dataset.calendarNote];if(configReady&&db&&state.uid)await setDoc(doc(db,"calendarNotes",state.uid),{notes:state.calendarNotes},{merge:true});renderCalendar();}); }
function changeCalendarMonth(offset) { const next = new Date(state.calendar.year, state.calendar.month + offset, 1), candidate = { year: next.getFullYear(), month: next.getMonth() }; if ((candidate.year < calendarMin.year || candidate.year === calendarMin.year && candidate.month < calendarMin.month) || (candidate.year > calendarMax.year || candidate.year === calendarMax.year && candidate.month > calendarMax.month)) return; state.calendar = candidate; renderCalendar(); }
function renderCounts() { ["pending","receiving","done"].forEach((s) => { $(s + "-count").textContent = state.items.filter((x) => x.type !== "submission" && itemStatus(x) === s).length; }); }
function renderGrading() { const rows = state.items.filter((x) => x.type !== "submission" && itemStatus(x) === state.status && (state.filter === "all" || category(x) === state.filter)); $("grading-list").innerHTML = rows.length ? rows.map((x) => { const d = asDate(x.deadline); const due = d ? new Intl.DateTimeFormat("vi-VN", { day:"2-digit", month:"2-digit", hour:"2-digit", minute:"2-digit", timeZone:"Asia/Ho_Chi_Minh" }).format(d) : vi.unset; return `<div class="grading-row"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(categoryLabel(x))}</small></div><span>${due}</span><label class="grade-check"><input type="checkbox" data-grade="${x.id}" ${x.graded ? "checked" : ""}> ${x.graded ? "Đã chấm" : "Đánh dấu đã chấm"}</label></div>`; }).join("") : `<p class="sub">${vi.none}</p>`; document.querySelectorAll("[data-grade]").forEach((input) => input.addEventListener("change", async () => { const item = state.items.find((x) => x.id === input.dataset.grade); item.graded = input.checked; if (configReady && db) await setDoc(doc(db, "practiceItems", item.id), { graded: item.graded }, { merge: true }); renderCounts(); renderGrading(); })); }
function renderNotes() { $("teacher-note").value = state.note.text || ""; $("todo-list").innerHTML = state.note.todos.map((x,i) => `<label class="todo-row"><span class="todo-text ${x.done ? "checked" : ""}">${escapeHtml(x.text)}</span><input type="checkbox" data-todo="${i}" ${x.done ? "checked" : ""} aria-label="Da hoan thanh">${state.deleteMode ? `<button type="button" class="todo-delete-row" data-delete-todo="${i}" aria-label="Xoa viec">−</button>` : ""}</label>`).join(""); $("delete-todo").classList.toggle("on", state.deleteMode); document.querySelectorAll("[data-todo]").forEach((input) => input.addEventListener("change", () => { state.note.todos[Number(input.dataset.todo)].done = input.checked; saveNotes(); renderNotes(); })); document.querySelectorAll("[data-delete-todo]").forEach((button) => button.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); state.note.todos.splice(Number(button.dataset.deleteTodo), 1); saveNotes(); renderNotes(); })); }
function startTodoEditor() { if ($("todo-editor")) return; const input = document.createElement("input"); input.id = "todo-editor"; input.className = "todo-editor"; input.type = "text"; input.autocomplete = "off"; input.setAttribute("aria-label", "Viec can lam"); $("todo-list").appendChild(input); input.focus(); let saved = false; const commit = () => { if (saved) return; saved = true; const text = input.value.trim(); if (text) { state.note.todos.push({ text, done:false }); saveNotes(); } renderNotes(); }; input.addEventListener("keydown", (e) => { if (e.key === "Enter") { e.preventDefault(); commit(); } if (e.key === "Escape") renderNotes(); }); input.addEventListener("blur", commit); }
async function saveNotes() { if (!state.uid || !configReady || !db) return; $("note-state").textContent = vi.saving; await setDoc(doc(db, "teacherNotes", state.uid), state.note, { merge:true }); $("note-state").textContent = vi.saved; }
async function loadData() { if (!configReady || !db) return; const [f,i,c] = await Promise.all([getDocs(collection(db,"practiceFolders")),getDocs(collection(db,"practiceItems")),getDoc(doc(db,"calendarNotes",state.uid))]); state.folders = f.docs.map((x) => ({id:x.id,...x.data()})); state.items = i.docs.map((x) => ({id:x.id,...x.data()})); state.calendarNotes = c.exists() ? (c.data().notes || {}) : {}; renderCalendar(); renderCounts(); renderGrading(); }
function openGrading(status="pending") { state.status=status; $("grading-modal").classList.remove("hidden"); document.querySelectorAll("[data-modal-status]").forEach((x) => x.classList.toggle("on", x.dataset.modalStatus === status)); renderGrading(); }
$("week-prev").onclick=()=>{$("school-week").value=state.week=Math.max(1,state.week-1);}; $("week-next").onclick=()=>{$("school-week").value=++state.week;}; $("school-week").onchange=(e)=>{e.target.value=state.week=Math.max(1,Number(e.target.value)||1);}; $("calendar-prev").onclick=()=>changeCalendarMonth(-1); $("calendar-next").onclick=()=>changeCalendarMonth(1); $("open-grading").onclick=()=>openGrading(); $("close-grading").onclick=()=>$("grading-modal").classList.add("hidden"); $("grading-modal").onclick=(e)=>{if(e.target===$("grading-modal")) $("grading-modal").classList.add("hidden");}; document.querySelectorAll("[data-status]").forEach((x)=>x.onclick=()=>openGrading(x.dataset.status)); document.querySelectorAll("[data-modal-status]").forEach((x)=>x.onclick=()=>openGrading(x.dataset.modalStatus)); $("grading-filter").onchange=(e)=>{state.filter=e.target.value;renderGrading();}; document.querySelectorAll("[data-note-tab]").forEach((x)=>x.onclick=()=>{const todo=x.dataset.noteTab==="todo";document.querySelectorAll("[data-note-tab]").forEach((b)=>b.classList.toggle("on",b===x));$("note-panel").classList.toggle("hidden",todo);$("todo-panel").classList.toggle("hidden",!todo);}); $("teacher-note").onchange=()=>{state.note.text=$("teacher-note").value;saveNotes();}; $("add-todo").onclick=startTodoEditor;
$("delete-todo").onclick=()=>{state.deleteMode=!state.deleteMode;renderNotes();};
renderCalendar(); $("school-week").value=state.week; renderNotes(); mountChrome({active:"home",role:"teacher",who:vi.teacher}); watchAuth(async(user,profile)=>{if(!user)return;state.uid=user.uid;mountChrome({active:"home",role:"teacher",who:(profile&&profile.hoTen)||user.email||vi.teacher});if(configReady&&db){const snap=await getDoc(doc(db,"teacherNotes",user.uid));if(snap.exists())state.note={text:"",todos:[],...snap.data()};renderNotes();await loadData();}});
function ensureNoteEditor(){if(document.getElementById("calendar-note-modal"))return;const w=document.createElement("div");w.id="calendar-note-modal";w.className="modal-back hidden";w.innerHTML='<section class="calendar-note-modal modal"><div class="panel-heading"><h2>Ghi chú</h2><button class="icon-control" id="close-calendar-note" type="button">&times;</button></div><label>Nội dung ghi chú</label><textarea id="calendar-note-input" rows="8" placeholder="Viết ghi chú cho ngày này..."></textarea><div class="calendar-note-actions"><button class="btn ghost" id="cancel-calendar-note" type="button">Hủy</button><button class="btn" id="save-calendar-note" type="button">Lưu ghi chú</button></div></section>';document.body.appendChild(w);document.getElementById("close-calendar-note").onclick=()=>w.classList.add("hidden");document.getElementById("cancel-calendar-note").onclick=()=>w.classList.add("hidden");document.getElementById("save-calendar-note").onclick=async()=>{const t=document.getElementById("calendar-note-input").value.trim();state.calendarNotes=state.calendarNotes||{};if(t)state.calendarNotes[window.__noteKey]=t;else delete state.calendarNotes[window.__noteKey];if(configReady&&db&&state.uid)await setDoc(doc(db,"calendarNotes",state.uid),{notes:state.calendarNotes},{merge:true});w.classList.add("hidden");renderCalendar();};}
document.addEventListener("contextmenu",(e)=>{const day=e.target.closest("[data-calendar-note]");if(!day)return;e.preventDefault();e.stopImmediatePropagation();ensureNoteEditor();window.__noteKey=day.dataset.calendarNote;document.getElementById("calendar-note-input").value=(state.calendarNotes||{})[window.__noteKey]||"";document.getElementById("calendar-note-modal").classList.remove("hidden");document.getElementById("calendar-note-input").focus();},true);
import "./week-sync.js";
