import { collection, doc, getDoc, getDocs, setDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { mountChrome } from "./shell.js";
import { watchAuth } from "./auth.js";
import { db, configReady } from "./firebase-init.js";
const $=id=>document.getElementById(id), today=new Date();
const state={uid:null,folders:[],items:[],progress:{},notes:{text:"",todos:[]},calendarNotes:{},calendar:{year:today.getFullYear(),month:today.getMonth()},status:"open",deleteMode:false};
const asDate=v=>{if(!v)return null;if(typeof v.toDate==="function")return v.toDate();if(v.seconds!=null)return new Date(v.seconds*1000);const d=new Date(v);return Number.isNaN(d)?null:d;};
const esc=v=>{const e=document.createElement("div");e.textContent=v||"";return e.innerHTML;};
const key=(y,m,d)=>`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
function assignments(){const byId=Object.fromEntries(state.folders.map(f=>[f.id,f]));return state.items.filter(i=>{let f=byId[i.folderId];while(f&&f.parentId)f=byId[f.parentId];return i.type!=="submission"&&f&&(f.kind==="baitap"||f.seedKey==="bai-tap"||/bài\s*tập/i.test(f.title||""));});}
const expired=i=>{const d=asDate(i.deadline);return !!d&&d<=Date.now();}; const complete=i=>expired(i)||!!state.progress[i.id];
function due(i){const d=asDate(i.deadline);return d?new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Ho_Chi_Minh"}).format(d):"Chưa đặt hạn";}
function renderCounts(){const a=assignments();$("open-count").textContent=a.filter(i=>!complete(i)).length;$("completed-count").textContent=a.filter(complete).length;}
function renderAssignments(){const rows=assignments().filter(i=>state.status==="completed"?complete(i):!complete(i));$("assignment-list").innerHTML=rows.length?rows.map(i=>{const checked=!!state.progress[i.id], urgent=(!expired(i)&&asDate(i.deadline)&&asDate(i.deadline)-Date.now()<=172800000)||(expired(i)&&!checked);return `<article class="grading-row assignment-row${urgent?" urgent":""}"><div><b>${esc(i.title)}</b><small>${urgent?"SẮP HẾT HẠN NỘP · ":""}Hạn nộp ${due(i)}${expired(i)?" · Đã hết hạn":""}</small></div><label class="grade-check"><input type="checkbox" data-progress="${i.id}" ${checked?"checked":""}> ${checked?"Đã hoàn thành":"Đánh dấu hoàn thành"}</label></article>`;}).join(""):'<p class="sub">Không có bài tập phù hợp.</p>';document.querySelectorAll("[data-progress]").forEach(el=>el.onchange=async()=>{state.progress[el.dataset.progress]=el.checked;if(configReady&&db&&state.uid)await setDoc(doc(db,"assignmentProgress",`${state.uid}_${el.dataset.progress}`),{studentId:state.uid,itemId:el.dataset.progress,completed:el.checked,updatedAt:new Date()},{merge:true});renderCounts();renderAssignments();});}
function renderCalendar(){const {year:y,month:m}=state.calendar;$("calendar-heading").textContent=`Tháng ${String(m+1).padStart(2,"0")} · ${y}`;$("calendar-prev").disabled=y===2024&&m===0;$("calendar-next").disabled=y===2030&&m===11;let h=["T2","T3","T4","T5","T6","T7","CN"].map(x=>`<span class="cal-weekday">${x}</span>`).join("");for(let i=0;i<(new Date(y,m,1).getDay()+6)%7;i++)h+="<span></span>";for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const k=key(y,m,d),note=state.calendarNotes[k],isToday=k===key(today.getFullYear(),today.getMonth(),today.getDate());h+=`<button type="button" class="cal-day${isToday?" today":""}${note?" has-note":""}" data-date="${k}"${note?` title="${esc(note)}"`:""}>${d}</button>`;}$("mini-calendar").innerHTML=h;document.querySelectorAll("[data-date]").forEach(e=>e.oncontextmenu=async ev=>{ev.preventDefault();const note=window.prompt("Thêm note",state.calendarNotes[e.dataset.date]||"");if(note===null)return;if(note.trim())state.calendarNotes[e.dataset.date]=note.trim();else delete state.calendarNotes[e.dataset.date];if(configReady&&db&&state.uid)await setDoc(doc(db,"calendarNotes",state.uid),{notes:state.calendarNotes},{merge:true});renderCalendar();});}
function renderNotes(){$("student-note").value=state.notes.text||"";$("todo-list").innerHTML=state.notes.todos.map((x,i)=>`<label class="todo-row"><span class="todo-text ${x.done?"checked":""}">${esc(x.text)}</span><input type="checkbox" data-todo="${i}" ${x.done?"checked":""}>${state.deleteMode?`<button class="todo-delete-row" type="button" data-delete="${i}">−</button>`:""}</label>`).join("");document.querySelectorAll("[data-todo]").forEach(e=>e.onchange=()=>{state.notes.todos[+e.dataset.todo].done=e.checked;saveNotes();renderNotes();});document.querySelectorAll("[data-delete]").forEach(e=>e.onclick=()=>{state.notes.todos.splice(+e.dataset.delete,1);saveNotes();renderNotes();});}
async function saveNotes(){if(!state.uid||!configReady||!db)return;$("note-state").textContent="Đang lưu…";await setDoc(doc(db,"studentNotes",state.uid),state.notes,{merge:true});$("note-state").textContent="Đã lưu";}
async function load(){if(!configReady||!db||!state.uid)return;const [f,i,n,c]=await Promise.all([getDocs(collection(db,"practiceFolders")),getDocs(collection(db,"practiceItems")),getDoc(doc(db,"studentNotes",state.uid)),getDoc(doc(db,"calendarNotes",state.uid))]);state.folders=f.docs.map(x=>({id:x.id,...x.data()}));state.items=i.docs.map(x=>({id:x.id,...x.data()}));if(n.exists())state.notes={text:"",todos:[],...n.data()};if(c.exists())state.calendarNotes=c.data().notes||{};const p=await Promise.all(assignments().map(i=>getDoc(doc(db,"assignmentProgress",`${state.uid}_${i.id}`))));p.forEach(x=>{if(x.exists())state.progress[x.data().itemId]=!!x.data().completed;});renderCounts();renderAssignments();renderNotes();renderCalendar();}
function month(n){const d=new Date(state.calendar.year,state.calendar.month+n,1);if(d<new Date(2024,0,1)||d>new Date(2030,11,1))return;state.calendar={year:d.getFullYear(),month:d.getMonth()};renderCalendar();}
$("calendar-prev").onclick=()=>month(-1);$("calendar-next").onclick=()=>month(1);$("open-assignments").onclick=()=>{$("assignment-modal").classList.remove("hidden");renderAssignments();};$("close-assignments").onclick=()=>$("assignment-modal").classList.add("hidden");$("assignment-modal").onclick=e=>{if(e.target===$("assignment-modal"))$("assignment-modal").classList.add("hidden");};document.querySelectorAll("[data-status]").forEach(e=>e.onclick=()=>{state.status=e.dataset.status;$("assignment-modal").classList.remove("hidden");document.querySelectorAll("[data-modal-status]").forEach(x=>x.classList.toggle("on",x.dataset.modalStatus===state.status));renderAssignments();});document.querySelectorAll("[data-modal-status]").forEach(e=>e.onclick=()=>{state.status=e.dataset.modalStatus;document.querySelectorAll("[data-modal-status]").forEach(x=>x.classList.toggle("on",x===e));renderAssignments();});document.querySelectorAll("[data-note-tab]").forEach(e=>e.onclick=()=>{const t=e.dataset.noteTab==="todo";document.querySelectorAll("[data-note-tab]").forEach(x=>x.classList.toggle("on",x===e));$("note-panel").classList.toggle("hidden",t);$("todo-panel").classList.toggle("hidden",!t);});$("student-note").onchange=()=>{state.notes.text=$("student-note").value;saveNotes();};$("add-todo").onclick=()=>{const t=window.prompt("Việc cần làm");if(t&&t.trim()){state.notes.todos.push({text:t.trim(),done:false});saveNotes();renderNotes();}};$("delete-todo").onclick=()=>{state.deleteMode=!state.deleteMode;renderNotes();};mountChrome({active:"home",role:"student",who:"Học sinh"});renderCalendar();renderNotes();watchAuth(async(u,p)=>{if(!u)return;state.uid=u.uid;mountChrome({active:"home",role:"student",who:(p&&p.hoTen)||u.email||"Học sinh"});await load();});
function ensureNoteEditor(){if(document.getElementById("calendar-note-modal"))return;const w=document.createElement("div");w.id="calendar-note-modal";w.className="modal-back hidden";w.innerHTML='<section class="calendar-note-modal modal"><div class="panel-heading"><h2>Ghi chú</h2><button class="icon-control" id="close-calendar-note" type="button">&times;</button></div><label>Nội dung ghi chú</label><textarea id="calendar-note-input" rows="8" placeholder="Viết ghi chú cho ngày này..."></textarea><div class="calendar-note-actions"><button class="btn ghost" id="cancel-calendar-note" type="button">Hủy</button><button class="btn" id="save-calendar-note" type="button">Lưu ghi chú</button></div></section>';document.body.appendChild(w);document.getElementById("close-calendar-note").onclick=()=>w.classList.add("hidden");document.getElementById("cancel-calendar-note").onclick=()=>w.classList.add("hidden");document.getElementById("save-calendar-note").onclick=async()=>{const t=document.getElementById("calendar-note-input").value.trim();if(t)state.calendarNotes[window.__noteKey]=t;else delete state.calendarNotes[window.__noteKey];if(configReady&&db&&state.uid)await setDoc(doc(db,"calendarNotes",state.uid),{notes:state.calendarNotes},{merge:true});w.classList.add("hidden");renderCalendar();};}
document.addEventListener("contextmenu",(e)=>{const day=e.target.closest("[data-date]");if(!day)return;e.preventDefault();e.stopImmediatePropagation();ensureNoteEditor();window.__noteKey=day.dataset.date;document.getElementById("calendar-note-input").value=state.calendarNotes[window.__noteKey]||"";document.getElementById("calendar-note-modal").classList.remove("hidden");document.getElementById("calendar-note-input").focus();},true);
